### ISSUE TITLE
FTBFS with OpenSSL >= 1.1

### ISSUE THREAD

**Issue by Vascom** [eiskaltdcpp/eiskaltdcpp#356] opened 2017-02-07 07:12 UTC
I am try build last version from git for Fedora 26 and have some build errors:

/builddir/build/BUILD/eiskaltdcpp-eiskaltdcpp-0fa9a73/dcpp/CryptoManager.cpp: In constructor 'dcpp::CryptoManager::CryptoManager()':
/builddir/build/BUILD/eiskaltdcpp-eiskaltdcpp-0fa9a73/dcpp/CryptoManager.cpp:112:15: error: invalid use of incomplete type 'struct dh_st'
             dh->p = BN_bin2bn(dh4096_p, sizeof(dh4096_p), 0);
               ^~
/builddir/build/BUILD/eiskaltdcpp-eiskaltdcpp-0fa9a73/dcpp/CryptoManager.cpp:113:15: error: invalid use of incomplete type 'struct dh_st'
             dh->g = BN_bin2bn(dh4096_g, sizeof(dh4096_g), 0);
               ^~
/builddir/build/BUILD/eiskaltdcpp-eiskaltdcpp-0fa9a73/dcpp/CryptoManager.cpp:115:19: error: invalid use of incomplete type 'struct dh_st'
             if(!dh->p || !dh->g) {
                   ^~
/builddir/build/BUILD/eiskaltdcpp-eiskaltdcpp-0fa9a73/dcpp/CryptoManager.cpp:115:29: error: invalid use of incomplete type 'struct dh_st'
             if(!dh->p || !dh->g) {
                             ^~

Full build log  http://koji.russianfedora.pro/kojifiles/work/tasks/3580/23580/build.log
Used components http://koji.russianfedora.pro/kojifiles/work/tasks/3580/23580/root.log

Please solve this problem so I can add eiskaltdcpp to Fedora repository.

**Comment by isage** [comment] 2017-02-07 07:41
This is caused by incompatibility with OpenSSL 1.1.0
As https://wiki.openssl.org/index.php/1.1_API_Changes states:
```Application code now has to use pointers, and cannot allocate objects directly on the stack.```
But, https://github.com/eiskaltdcpp/eiskaltdcpp/blob/master/dcpp/CryptoManager.h#L65

**Comment by pavelvat** [comment] 2017-02-11 21:25
Now ```eiskaltdcpp-qt``` crashes on exit from program.
```bt``` and ```bt full```:
https://gist.github.com/pavelvat/00fa1d9cfd69d425290c11a98b99d875
It is 100% reproducible even after ```rm -rf ~/.config/eiskaltdc++/```.

This problem is not present on previous commit. But previous commit is not built (on current Debian unstable) with the same error how in first message https://github.com/eiskaltdcpp/eiskaltdcpp/issues/356#issue-205806095. It can be solved by: ```apt install libssl1.0-dev```.

Build  3b9c502 with libssl1.0 also crashes on exit from program.
```bt``` and ```bt full```:
https://gist.github.com/pavelvat/41f0b83ba133361329c83a9d7085aca6

**Comment by pavelvat** [comment] 2017-02-14 00:23
The program crashes are caused by this two strings:
https://github.com/eiskaltdcpp/eiskaltdcpp/blob/3b9c502ff5c98856d4f8fdb7ed3c6ef34448bfb7/dcpp/CryptoManager.cpp#L128-L129

**Comment by tehnick** [comment] 2017-10-07 17:43
@pavelvat Thanks for a note. Should be fixed in 45b5fa1a708eab077361700f4d1a1bc5e5a4b9ba.

**Closed by tehnick** 2017-10-07 17:43 UTC
